/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffddb8',
        'on-secondary': '#003824',
        'on-primary-container': '#006970',
        'on-error': '#690005',
        'on-tertiary': '#472a00',
        'on-tertiary-container': '#855300',
        outline: '#849495',
        'primary-container': '#00f0ff',
        background: '#10131a',
        'on-primary': '#00363a',
        'surface-dim': '#10131a',
        'on-background': '#e1e2eb',
        'on-tertiary-fixed': '#2a1700',
        'surface-bright': '#363940',
        'surface-container-highest': '#32353c',
        'on-secondary-fixed': '#002113',
        'surface-tint': '#00dbe9',
        'on-surface': '#e1e2eb',
        'secondary-container': '#00a572',
        'on-surface-variant': '#b9cacb',
        'primary-fixed-dim': '#00dbe9',
        'surface-container-high': '#272a31',
        'on-tertiary-fixed-variant': '#653e00',
        'outline-variant': '#3b494b',
        'tertiary-container': '#ffd19c',
        primary: '#dbfcff',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-container-lowest': '#0b0e14',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-low': '#191c22',
        'on-error-container': '#ffdad6',
        'surface-container': '#1d2026',
        'error-container': '#93000a',
        'surface-variant': '#32353c',
        'on-primary-fixed': '#002022',
        tertiary: '#fff3ea',
        'inverse-primary': '#006970',
        surface: '#10131a',
        'inverse-surface': '#e1e2eb',
        error: '#ffb4ab',
        'secondary-fixed': '#6ffbbe',
        'primary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#4edea3',
        'inverse-on-surface': '#2e3037',
        secondary: '#4edea3',
        'on-secondary-container': '#00311f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-page': '24px',
        gutter: '16px',
        'stack-md': '16px',
        'container-padding': '12px',
        unit: '4px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'data-lg': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'data-lg': ['20px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
